//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jeff.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageConfiguration
    {
        public long PageConfigurationIdentifier { get; set; }
        public string Page { get; set; }
        public string Text { get; set; }
        public string EmailAddress { get; set; }
        public string MediaName { get; set; }
        public string MediaUrl { get; set; }
    }
}
